version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

  angular:
    container_name: angular
    build: ./frontend
    restart: always 
    ports:
      - 4200:4200
    depends_on:
      - angular

  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: final
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  springboot:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    volumes:
      - ./springboot:/springboot
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker